# -*- coffee -*- -p
author: YC <yinso.chen@gmail.com>
name: run-cmd
description: A simple shell command builder and runner
version: 0.1.1
repository:
  type: git
  url: git://bitbucket.org/yinso/run-cmd.git
main: ./lib/main
engines:
  node: '>= 0.8.4'
scripts:
  test: make test
  prepublish: make
dependencies:
  yargs: =1.3.2
  coffee-script: =1.8.0
  underscore: =1.7.0
  loglet: '>=0.1.1'
devDependencies:
  testlet: '>= 0.2.0'
  coffee-bean: '>=0.3.0'
