// Generated by CoffeeScript 1.4.0
(function() {
  var compile, escape, loglet, regex;

  loglet = require('loglet');

  compile = function(program, args) {
    var arg, cmd, escaped;
    escaped = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = args.length; _i < _len; _i++) {
        arg = args[_i];
        _results.push(escape(arg));
      }
      return _results;
    })();
    cmd = [program].concat(escaped).join(' ');
    loglet.debug('cmd.compile', cmd, program, args);
    return cmd;
  };

  regex = /([^a-zA-Z0-9])/g;

  escape = function(arg) {
    return arg.replace(regex, '\\$1');
  };

  module.exports = {
    compile: compile,
    escape: escape
  };

}).call(this);
